[build]
builder = "NIXPACKS"
buildCommand = "npx tinacms build --local --skip-indexing && next build"

[deploy]
startCommand = "next start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
